/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lesson8EventsSol from "./Lesson8_Events.sol";
export type { lesson8EventsSol };
export type { Bank } from "./Bank";
export * as factories from "./factories";
export { Bank__factory } from "./factories/Bank__factory";
export type { Lesson8_EventsBank } from "./Lesson8_Events.sol/Lesson8_EventsBank";
export { Lesson8_EventsBank__factory } from "./factories/Lesson8_Events.sol/Lesson8_EventsBank__factory";
